- src/NoteForm.js
When trying to save a new note when one already exists the props override and the new note never saves.
> fixes notes bug

- package-lock.json
- package.json
- src/App.js
- src/components/Header.js
- src/components/Login.js
- src/config.js
- src/hoc/AuthHOC.js
- src/index.js
- src/lib/identityActions.js
- src/lib/identityActions.test.js
- src/tests/Header.test.js
I tried to make this minimally invasive, but it's a bigger change than I was hoping. The good news is, it's mostly deletions!
I moved the logic for knowing if a user is logged in or not to the top of the app, so `App` no longer needs to be wrapped in a `graphql` component. I also removed the use of local storage (other than the onegraph-auth token). On first starting, the app will make a call to GitHub to see if the user is logged in - if so, it uses the email/id pairing from the JWT and renders the inner app. If not, it displays the `Login` component.
I also updated the tests to pass with the new changes, but I did struggle with the eslint rules though, especially for the class constructs.
Happy to work on this some more if it looks like a direction you'd like to take it in! If so, I'd …
> Add GitHub login, rework data flow

- src/components/Header.js
Update header profile url to match user's login name.
The current state has `https://github.com/bdougie` as static link.
> Fix header profile url to logged user's

- .github/workflows/nodejs.yml
- package.json
* Bump @primer/components from 14.3.1 to 15.0.1 (#318) @dependabot-preview
* Bump filesize from 5.0.2 to 5.0.3 (#313) @dependabot-preview
* Bump dotenv from 8.1.0 to 8.2.0 (#317) @dependabot-preview
* Bump @storybook/addon-actions from 5.2.3 to 5.2.4 (#311) @dependabot-preview
* Bump stylelint from 11.0.0 to 11.1.1 (#314) @dependabot-preview
* Bump @babel/core from 7.6.2 to 7.6.4 (#310) @dependabot-preview
* Bump @primer/octicons-react from 9.1.1 to 9.2.0 (#312) @dependabot-preview
* Bump react-apollo from 3.1.2 to 3.1.3 (#315) @dependabot-preview
* Leveraging more react hooks (#286) @bdougie
> bump version

- src/lib/apiGraphQL.js
1. manually tested, repo gets created as private.
2. ```npm test``` passes all test suites
> open-sauced-goals repo gets created with visibility as private by default

- .github/workflows/nodejs.yml
- .github/workflows/storybook.yml
Per the community forum. A personal access token needs to be used to have 3rd party Actions run. 
https://github.community/t5/GitHub-Actions/GitHub-Actions-Not-Run-on-PR-Generated-by-GitHub-Actions/td-p/37482
> Add bdougie token

- src/components/RepositoryGoals.js
This fixes a few problems.
1. Widths were all broken due to React.Fragment does not respect the same qualities as a div. 
2. The more verbose check for repository does not account for null and was failing for any login that had not created a repository. I had to go back to the && check
> Fix all broken widths

- src/lib/reducers.test.js
As soon as I posted my experience on Twitter, I received [some feedback]([https://twitter.com/hugo__df/status/1215768310131908610](https://twitter.com/hugo__df/status/1215768310131908610)) that my test would still pass if the function stopper throwing the error. Instead I was recommended to [fail fast with Jest](https://codewithhugo.com/jest-force-explicitly-fail-test/). Failing fast is using [toThrow()](https://jestjs.io/docs/en/expect#tothrowerror), which I originally attempted. My mistake when trying out this expectation was not [binding the function](https://www.geeksforgeeks.org/javascript-function-binding/) to provide the error.
> improve reducer error tests

- src/styles/Grid/Flex.js
I discovered that the following was overriding the flexbox.
```
display: -webkit-box;	
display: -moz-box;
```
closes #455
> removes box-css

- src/components/CreateGoals.js
- src/components/NoteForm.js
- src/components/RepositoryGoals.js
fixes #524 
The migration from lifecycle methods to hooks introduced a number of bugs. In this case, the id of the created "open-sauced-goals" repo was not being stored in globalState (context) of the App. This id is needed to do anything because the repo is the backbone (of the database for this project). 
I am passing the id directly to the `onRepoCreatio` callback. I am not relying on the `goalsReducer` to do this because I want this update to happen immediately. 
While testing another page to see how the back updates to components worked, I found that the **NoteForm.js** deletion handler was not updating. Also due to a switch to using hooks. I move the `Redirect` into the main render to fix it.
> bug fix(#524) Failure when adding repos after the initial goals repo creation.

- src/components/CreateGoals.js
- src/lib/apiGraphQL.js
I originally planned to have this project make private repos on behalf of the user. IMO open source contributions are easier when you explicitly state you are looking to help, which is why I am switching this flag to be open by default.
> Make open-sauced-goals public by default

- src/components/Repository.js
Add loading until repo name loads, I think spinner is not suitable here!
> Add loading until repo name loads

- src/components/AddRepoForm.js
This turns the add repo input into a form element. This way the `_handleGoalCreation` function runs when the form is sumbitted, which can be done by pressing either the sumbit button or return key.
#554
> Allow return key to add repositories

- src/components/Hero.js
- src/styles/Grid/GridColumns.js
- src/styles/Grid/index.js
- src/styles/Header/Hero.js
This PR adds a styled component called `GridColumns`, which allows you to pass in a number of columns for `grid-template-columns` & also uses `display: grid`. By default, without a `columns` prop value, `grid-template-columns` will just repeat 1 column.
I think this type of change would be useful to the "details" section of the `Hero` component. Since that part of the page has content with varying height, `display: grid` will help ensure that each "detail" section is aligned by making the content conform to the grid layout.
In summary:
- `GridColumns` styled component
- Replaced `FloatLeft`, `FloatRight`, and `Flex` usage in the "details" section of the `Hero` component with the new `GridColumns` styled component
- Changed image styles for the "details" section from `float: left` to …
> Fix hero details columns

- src/index.js
- src/lib/validateToken.js
- src/lib/validateToken.test.js
Fixes issue where the app will crash if the OneGraph token was expired and the LoggedInStatus is set to true. 
The fix is to validate the token by checking the expireDate when setting the LoggedInStatus.
fixes: #807
> Fix Issue #807:  App crashes if OneGraph token has expired

- src/components/Nav.js
Right now, if you use the "tab" key to navigate through the page, the Login/Logout links are skipped (they are `<a>` tags w no `href` so they are skipped in tabbing). This adds `tabindex` to fix that behavior.
I also cleaned up the `alt` attribute on that link because `alt` is not a valid attribute for `a` links (and it looks like they were being misused as descriptions of what an alternate link would be and not even the `title` of the link).
no
> fixing nav menu links to have tabIndex

- README.md
Indent the coding sections under Contributing in the ReadMe TOC
GitHub is rolling our a shiny new table of contents features to ReadMe files. This is a small change so that the coding related activities are indented under the main contributing section of the readme with-in the table of contents so it looks like this:
None
None
> docs: Reformat readme

- .github/workflows/compliance.yml
Update pr-compliance-action from v0.2.1 to v0.5.0
Resolves #1351 
There have been several feature releases since v0.2.1. 
- In v0.3.0 we use the default branch if `protected-branch` is not specified. 
- In v0.4.0, we use `secrets.GITHUB_TOKEN` if `repo-token` is not specified. 
- In v0.5.0, the action is less "chatty" as it uses reviews instead of regular comments and it updates the existing review instead of leaving additional comments.
> feat: Update pr-compliance-action

- README.md
This PR fixes the dependabot badge not loading in the README file. 
Fixes #1365
> fix: README Badge not loading (dependabot)

- index.html
- Feature
- This PR adds Social Cards as requested in https://github.com/open-sauced/open-sauced/issues/1347 by implementing Open Graph Protocol meta tags for social medias like facebook, linkedin and twitter.
- For testing purpose, used google extension localhost open graph checker that provides temporary url for checking.
- This PR closes #1347
1. Facebook
- Meta tag supported on facebook are supported on linkedin as well
2. Twitter
-  Meta tag supported on Twitter
No tests were added but all previous tests were passed.
No Documentation was necessary.
- Social Card contains image, title and description too. Clicking on the post will redirect you to https://app.opensauced.pizza
> feat: added social cards

- src/components/AddRepoForm.jsx
- src/lib/repoStatusCode.js
- src/lib/repoStatusCode.test.js
- src/styles/Button.jsx
This PR fixes #1460 and fixes #1462.
This PR disables the repo add button while the goal adding API request is in flight.
The scope moved around a little on this one because I found little things to do as I went.
- changes the style on `InputButton` in the disabled state, so the cursor isn't the only visual indication.
- adjusts the comparison with existing goals to use lowercase since `isValidRepoUrl()`
- returns new full name with 301 status code from `repoStatusCode()` and pre-fills the form input with it
- fixes tests for new return for for `repoStatusCode()`.
#1460, #1462
These are screenshots with the button duplicated with disabled state (just to show the difference, the app still only has one button).
> fix: avoid duplicate repos
