open-sauced/open-sauced

- config/env.js
- config/jest/CSSStub.js
- config/jest/FileStub.js
- config/paths.js
- config/polyfills.js
- config/webpack.config.dev.js
- config/webpack.config.prod.js
- package.json
- scripts/build.js
- scripts/start.js
- scripts/test.js
- src/Count.js
- src/Form.js
- src/index.css
>  fix annoyances

- config/env.js
- src/Form.js
- src/lib/apiGraphQL.js
> working env var setup

- README.md
- public/index.html
- src/Dropdown.js
- src/Instructions.js
- src/NewRepoForm.js
- src/Repositories.js
added instructions component
better error handling
> Random cleanup

- package.json
- src/NewRepoForm.js
- src/Repositories.js
- yarn.lock
**- Summary**
Attempting to fix #17 
Repo steps in issue #17 
Update to help refetching after mutate repositories array
> attempt to fix refetching

- src/NoteForm.js
- src/index.css
#21 
**- Summary**
**- A picture of a cute animal (not mandatory but encouraged)**
> delete button working

- src/Repository.js
Just adds more data to the repo page.
> adds more data

- CONTRIBUTING.md
> removes references to cms in contributing.md

- .eslintrc
- package-lock.json
- src/Issues.js
- src/NoteForm.js
- src/Repository.js
- src/lib/apiGraphQL.js
- yarn.lock
#18 
**- Summary**
Adds issues to an Issues component. I hit the rate limit, so spiking on this for now.
Issues are being queried when the component mounts and has a repo owner. I am curious if it is worth adding the GitHub endpoint to the Apollo Client. I am still learning my way through it and will explore that when I get there.
Adds issues to open-sauced
> adds issues to page

- src/App.css
- src/App.js
- src/Issues.js
- src/NoteForm.js
- src/icons/chevron-left.svg
- src/icons/chevron-right.svg
- src/icons/index.js
- src/styles/Grid/FlexCenter.js
- src/styles/Grid/FormColumn.js
- src/styles/Grid/IssuesColumn.js
- src/styles/Grid/index.js
- src/styles/PointerLink.js
- src/styles/Typography/TinyFont.js
- src/styles/Typography/index.js
- src/styles/variables.js
> adds styling to issues

- package.json
- src/components/Footer.js
- src/icons/monitor.svg
- src/styles/Grid/IssuesColumn.js
**- Summary**
**- A picture of a cute animal (not mandatory but encouraged)**
> updated style components

- src/App.js
- src/components/Login.js
**- Summary**
This is a PR to add to save the Open Sauced user to local storage. I am not using redux, since things got complicated very fast  
Click the deploy preview and login, and then logout.
save user to local storage
> working login save to localStorage

- src/App.js
- src/components/Header.js
- src/tests/Header.test.js
> moves header section to a component

- .eslintrc
- package.json
- yarn.lock
> fixes broken netlify build

- README.md
- config/webpack.config.prod.js
- netlify.toml
- package.json
- public/manifest.json
- src/index.js
- src/registerServiceWorker.js
- src/service-worker.js
- yarn.lock
**- Summary**
I added a basic service-worker to the project that mirrors the service work that is in Create React App. It is not clear in the CRA readme, but a service-worker.js is needed for it to work there. I think I might need to PR an FYI there. The service worker only works in production, which I have done so on this URL. https://59dbc9dda6188f2c0aa13db5--open-sauced.netlify.com/
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app 
#48 
Visit the https://59dbc9dda6188f2c0aa13db5--open-sauced.netlify.com/ and confirm a service is registered
Adds simple offline service worker for caching
> adds service worker

- src/components/Footer.js
- src/components/Header.js
- src/icons/alert-circle.svg
- src/icons/index.js
- src/icons/log-in.svg
- src/icons/log-out.svg
- src/styles/Grid/FloatLeft.js
- src/styles/Grid/index.js
Add a link to create issues from the nav
> enhance the nav

- package-lock.json
- package.json
somehow got test passing without adding this library
> adds missing mock library

- .github/workflows/nodejs.yml
https://github.com/features/actions
> add CI via actions

- package-lock.json
- package.json
- src/App.js
- src/components/Header.js
- src/config.js
Removing some annoying things about this project
> Project cleanup

- README.md
- src/components/Footer.js
In preparation for completing #117 I am removing some old information from the README and footer of the site.
> Remove prisma link

- src/containers/Goals.js
- src/containers/NoteForm.js
https://github.com/bdougie/open-sauced/issues/215
https://github.com/bdougie/open-sauced/issues/216
https://github.com/bdougie/open-sauced/issues/213
https://github.com/bdougie/open-sauced/issues/214
> migrates todos to issues

- src/components/Header.js
> updates link to profile

- src/components/ListGoals.js
- src/containers/Goals.js
- src/containers/NoteForm.js
- src/containers/Repositories.js
- src/containers/Repository.js
> working note rendering

- .storybook/addons.js
- .storybook/config.js
- package-lock.json
- package.json
- stories/0-Welcome.stories.js
- stories/1-Button.stories.js
Making it easier to design and prevent rate  limiting #208
> adds storybook

- src/index.css
Update, body div width **_CHANGE TO_** auto
> Content centering index.css

- src/containers/Goals.js
> Add empty object as fallback for goals response

- package.json
- src/components/Header.js
- src/index.css
- src/styles/Grid/Float.js
- src/styles/Grid/index.js
> fix the header

- src/components/Login.js
- src/styles/Container.js
- src/styles/Grid/Flex.js
- src/styles/Grid/index.js
- src/styles/Label.js
> fix mobile view

- src/containers/NewRepoForm.js
- src/containers/NoteForm.js
- src/index.css
- src/styles/Button.js
- src/styles/Grid/IssuesColumn.js
- src/styles/Input.js
- src/styles/TextArea.js
- stories/1-Button.stories.js
- stories/2-Card.stories.js
> update note style

- package.json
* update note style (#341) @bdougie
* fix mobile view (#340) @bdougie
* 337 repo cards (#338) @bdougie
* fix the header (#336) @notBdougie
* mobile friendly header and notes (#335) @bdougie
* Add storybook components (#334) @bdougie
> bump v0.9.3

- src/components/AddRepoForm.js
- src/components/Header.js
- src/components/ListGoals.js
- src/styles/Button.js
- src/styles/Card.js
- src/styles/Grid/Flex.js
- src/styles/Grid/index.js
- src/styles/Input.js
- src/styles/List.js
- stories/2-Card.stories.js
> add repo form

- .github/workflows/nodejs.yml
Updating caching per new version
https://github.com/actions/cache/blob/master/examples.md#node---npm
> Update caching to v1

- src/components/AddRepoForm.js
- src/styles/Button.js
> update new repo button

- src/components/AddRepoForm.js
- src/lib/util.js
- src/tests/util.test.js
1. added a method to check the validity of the url, and get relative repo url.
2. added test cases for the same.
Please suggest me if there is better way to do it. would appreciate if you can give me any suggestion/feedback on test cases.
Thanks!
closes #354
>  add a sanitizer to properly remove the base url

- .storybook/addons.js
- .storybook/config.js
- .storybook/webpack.config.js
- package-lock.json
- package.json
> 350 storybook addons

- src/tests/App.test.js
> 246 integration test

- package-lock.json
- src/styles/Card.js
- stories/2-Card.stories.js
> Storybook tweaks

- package-lock.json
- src/styles/Card.js
- stories/2-Card.stories.js
Adds a test for the new component added from #374
> Issue list test

- src/tests/IssueListItem.test.js
The first time was pushed with no new changes.
> redo: adds issues list test

- CONTRIBUTING.md
Adding some context to CONTRIBUTING.md in anticipation for future contributions.
> Update CONTRIBUTING.md with communication guides

- src/components/AddRepoForm.js
- src/components/Goals.js
- src/components/ListGoals.js
- src/lib/apiGraphQL.js
Issue addressed: As a user I should create a new goal and see it populate in the list without refreshing the page
#348
> Issue 348/draft

- src/components/IssueListItem.js
- src/components/Issues.js
- src/styles/Card.js
- src/tests/IssueListItem.test.js
- src/tests/mocks/data.js
- stories/2-Card.stories.js
close #386 
partially fixes #262 by removing the dependency on issues when the component renders
https://github.com/bdougie/open-sauced/pull/393/commits/ad08e77a9be5775b322b45e0fc3e13d71b84daf7
> 386 issues ui

- src/components/RepositoryGoals.js
- src/containers/Dashboard.js
- src/tests/RepositoryGoals.test.js
> complete rename of goals

- src/components/Issues.js
- src/components/ListGoals.js
- src/components/NoteForm.js
- src/components/Repository.js
- src/styles/Card.js
- src/styles/Grid/Flex.js
- src/styles/Grid/FormColumn.js
- src/styles/Grid/IssuesColumn.js
There were a few things noticeably broken in the CSS after adding the issues component styling.
The main thing was widths and flexbox usage.
> fix repository styles

- .eslintrc
- src/components/CreateGoals.js
- src/components/ListGoals.js
- src/components/RepositoryGoals.js
- src/lib/apiGraphQL.js
closes #348 
Followed the pattern created by @NileshPatel17 in #383 to ensure that the components update when a goal repo is created.
> 348 repo creation

- .github/workflows/assign-yourself.yml
- CONTRIBUTING.md
Saw this implementation used in pandas-dev/pandas and want to use it for the open-sauced contribution workflow.
> Add self assigner

- src/components/RepositoryGoals.js
> set goalsId upon repo creation

- src/styles/Card.js
- src/styles/Grid/IssuesColumn.js
fixes #403 
also fixes a margin issue for the ListGoals Compnent.
> 403 fix broken margin

- src/components/Repository.js
- src/styles/Typography/ErrorMessage.js
- src/styles/Typography/index.js
I discovered that two error have started happening with specific repos. 
1. When a repo has been renamed, the app does not render any data or errors.
2. When a org requires SAML tokens it does not load of show an error. 
1. I added an error handler to catch both types of errors
2. Create an Error style to print errors on the page.
> Error handling

- .github/workflows/storybook.yml
> Leverages paths in storybook.yml workflow

- src/lib/reducers.test.js
- src/tests/mocks/data.js
closes #409 
This is my attempt to create consistency in my test plan and have a structure for the 1 reducer I am using for the app.
> adds reducer tests

- package-lock.json
- package.json
Cheeky, I know, but I am actually no longer using emotion (style library) and this theming is not needed.
> The saddest PR to "remove emotion"

- .github/workflows/storybook.yml
Updates the action to see if that fixes it.
> update storybook static

- src/styles/Header/HomePageHeader.js
- src/styles/Header/index.js
- stories/6-Login.stories.js
> style componentize the header

- src/components/AddRepoForm.js
- src/components/Hero.js
- src/tests/AddRepoForm.test.js
- Read the Story Button
/cc @bdougie
> Add some Icons

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Inspired from https://github.com/thepracticaldev/dev.to Issue and PR template
/cc @bdougie
> Add Issue and PR Template

- package-lock.json
- package.json
- src/components/NoteForm.js
Add markdown for notes
Closes #473 
https://www.loom.com/share/04ac04e8429940aaa4ebe862d7342d44
no
> Add markdown for notes

- src/components/Nav.js
- src/styles/Header/HomeNav.js
- src/styles/Header/index.js
- src/styles/ProfileAvatar.js
- src/styles/Typography/SubtleLink.js
New Navbar Design
Closes #539, Closes #540
> New Navbar

- src/components/Hero.js
- src/components/IssueListItem.js
- src/components/RepositoryGoals.js
- src/index.css
- src/lib/apiGraphQL.js
- src/styles/Card.js
- src/styles/Header/Hero.js
- src/styles/Header/index.js
- src/styles/Spinner.js
> New homepage

- package.json
* Homepage copy updates and css improvements (#569) @bdougie
* Better list (#562) @yg
* Add cancel button (#565) @yg
* Issues empty placeholder (#561) @yg
* Better README (#559) @yg
* Update README.md (#558) @bdougie
* Allow return key to add repositories (#557) @Brawrdon
> release v0.13.0

- src/components/Nav.js
- src/tests/Nav.test.js
Bug where a user can navigate to a  
Fixes #571
> Redirects to "/" after logout

- src/components/Nav.js
> Shorten the avatar url

- .github/release-drafter.yml
- CONTRIBUTING.md
I am adding more features to the release drafter. To help with shipping bug fixes to production faster, we will need to start labeling our PRs accordingly for the release notes can be cut. 
This is in response to https://github.com/open-sauced/open-sauced/issues/579#issuecomment-638808972
> Improve release-drafter.yml

- .github/release-drafter.yml
Quick PR to be inclusive of the documentation label.
> Add documentation label to the release-drafter.yml template

- package-lock.json
- src/components/Issues.js
- src/components/ListGoals.js
- src/components/RepositoryGoals.js
- src/styles/EmptyPlaceholder.js
Add an empty placeholder for goals
Closes #608 
https://www.loom.com/share/61d3dba97eb94f0396a49f867cda341a
> Add an empty placeholder for goals

- package-lock.json
- src/index.js
> Admin bar will not show when logged out

- src/components/NoteForm.js
> User can now delete the note entirely

- src/components/Contributions.js
- src/styles/Spinner.js
Add spinner for contributions in repository page
https://www.loom.com/share/c806cf9c5e24456aaab57e7b32f39be4
> Add spinner for contributions

- CONTRIBUTING.md
Just fixed some grammar mistakes while reading through the contributing.md
None.
None.
None.
> fix: grammar in contributing.md

- CODE_OF_CONDUCT.md
Rewrite HTTP URLs in CODE_OF_CONDUCT.md to HTPPS.
> Upgrade links to HTTPS

- package-lock.json
- src/components/Hero.js
- src/styles/Header/Hero.js
Fixed #631 
In `Chrome` also: Auther's Name going outside of the flexbox
After Changing 
`Firefox`:
`Chrome` :
> Fixed Quote Author's Name Issue

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
We use a lot of emoji's in the project and even include gifs. So it thinks it would be cool if we added emojis to issues templates also.
This PR falls in the **other** category but no options are there for the PR template. So I also added an **other** option.
None.
None.
None.
https://i.pinimg.com/originals/4e/a8/2f/4ea82f283540b39e82229317c404b09d.gif
> Added Emojis to Issue and PR templates

- CONTRIBUTING.md
- src/components/AdminStatsBar.js
- src/components/Contributions.js
- src/components/Hero.js
- src/components/Issues.js
- src/components/Nav.js
- src/components/Repository.js
- src/components/RepositoryGoals.js
- src/containers/App.js
- stories/4-Nav.stories.js
Links to cross-origin destinations are unsafe
https://web.dev/external-anchors-use-rel-noopener/
Mentioned in the discord.
I am going to add a the https://github.com/jakejarvis/lighthouse-action to start testing new deploy preview PRs.
> add rel=noreferrer to all target="_blank"

- .github/workflows/lighthouse.yml
Testing out lighthouse testing for PRs.
#647 
Coming soon
> Add lighthouse.yml

- CONTRIBUTING.md
When I was reading the contributing docs, I noticed two small typos and then a reference to a command (`npm run lint`) that is currently not defined/available in the `package.json`.
None. I hope you don't mind an unsolicited edit for this file. 😅 
N/A
N/A
> Update contributing docs to remove command and fix typo

- CONTRIBUTING.md
- README.md
Update the discord invitation sentence
> Update the discord invitation line

- src/components/Repository.js
- src/components/RepositoryGoals.js
Add number of languages shown as a constant variable
> Add number of languages as a const

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Update labels in issue templates
> Update labels in issue templates

- src/styles/variables.js
Get rid of that space in the micro variable string
> The annoying micro-space

- .github/workflows/lighthouse.yml
Checks to see if Netlify has completed before proceeding with the audit. 
There have been failures in the past, but re-running the workflows fixes it. 
Check future PRs for blocks or failures.
> prevents audit CI until netlify completes

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- CONTRIBUTING.md
I am noticing a high number of PRs are coming through without any linked issues tr discussion. For small changes this is fine, but for changes to lines and how we decide to write code, I believe we should have contributors and team members to weigh in on the changes proposed. 
Thanks for your understanding.
> First PR considerations

- src/components/Issues.js
- src/components/Repository.js
- src/lib/apiGraphQL.js
#708 
For now, we just showed **issue not enabled** placeholder and PR count if issues are disabled
In the future, we can show list of PRs if issues are disabled #453
Partially Fixes #708
> Add placeholder and PR count if issues are disabled

- src/components/RepoListItem.js
Add "sync in progress" in star's placeholder
Closes #722
> Add "sync in progress" in star's placeholder

- src/components/Repository.js
- src/styles/Card.js
https://github.com/open-sauced/open-sauced/pull/707#issuecomment-645828660
> styles the triage button

- package-lock.json
- src/components/AddRepoForm.js
- src/lib/repoStatusCode.js
- src/lib/repoStatusCode.test.js
Add repo check validation
https://www.loom.com/share/158712dec5db4567b9f4e6b0ec342100
Fixes #654
> Add repo check validation

- src/components/Repository.js
- src/lib/apiGraphQL.js
Add license in repo meta card #734
Closes #734
> Add license in repo meta card

- src/components/Repository.js
- src/lib/apiGraphQL.js
Add repo description in the context box #732
Closes #732
> Add repo description in context box

- package-lock.json
- package.json
- src/components/DetailInfo.js
- src/components/IssueListItem.js
- src/components/Issues.js
- src/components/NoteForm.js
- src/components/RepoListItem.js
- src/components/Repository.js
- src/components/RepositoryGoals.js
> Feature: Icons moved to Octicons v10.0.0

- src/styles/NotFound.js
Update the font on the 404 page, it was inhering the font from the Hero.js style.
> Correct the font on 404

- package-lock.json
- package.json
- src/components/IssueListItem.js
- src/lib/colorContrast.js
Co-Authored-By: @bdougie, @yg 
Change the current font color based on contrast of the background (label) color and the text.
Closes #658
> Set color of text based on contrast

- .github/workflows/welcome.yml
Add a workflow to greet new contributors with a reply of their first PR
```md
Congrats on making your first Pull Request to Open Sauced! 🎉🍕
Join the conversation in our [Discord](https://discord.gg/gZMKK5q)
Thanks for taking the time to improve Open Sauced! ❤️
```
Closes #767
> Add a workflow to welcome new contributors

- src/components/Repository.js
- src/containers/Dashboard.js
- src/tests/Repository.test.js
#771 is blocked due to a test change. This fix will remove the dependency of having getUserFromJwt in the Repository.js. This will make the test more flexible.
#771
> Decouple getUserFromJwt from Repository.js

- src/components/RepoListItem.js
There was a bug when having a repo with 0 stars, it would just display a "`Sync in Progress`" label
Closes #766 
| Before | After |
|-------|-------|
| ![before](https://user-images.githubusercontent.com/29888641/86768828-6e602c00-c04e-11ea-9ca1-80a1ef847669.png) | ![after](https://user-images.githubusercontent.com/29888641/86768796-62746a00-c04e-11ea-8b4b-b92ad1aed982.png) |
> Fix non-working 0 star repos

- .github/release-drafter.yml
The release.yml broke when emojis were added to the labels. 
n/a
> updates the broken release.yml labels

- package-lock.json
- src/components/Repository.js
Fix fork button that is always disabled
And also fixed this https://github.com/open-sauced/open-sauced/pull/776#issuecomment-654842794
Closes #783
> Fix fork button

- src/lib/repoStatusCode.js
- src/lib/repoStatusCode.test.js
Add test for 301 status in repoStatusCode.test.js
Closes #737
> Add test for 301 status in repoStatusCode.test.js

- .github/PULL_REQUEST_TEMPLATE.md
Correct the grammar in the PR template, because Grammarly was going crazy every time I made one.
> Correct grammar

- src/containers/App.js
Add required URL parameters, so that passing invalid arguments doesn't break the whole thing.
Fixes #688
> Add required params

- .github/workflows/assign-yourself.yml
> Update assign-yourself.yml to use bdougie/take-action

- src/styles/Button.js
- src/styles/Card.js
- src/styles/EmptyPlaceholder.js
- src/styles/Header/AdminNav.js
- src/styles/Header/Hero.js
- src/styles/Header/HomeNav.js
- src/styles/List.js
- src/styles/NotFound.js
- src/styles/Typography/AccentLink.js
- src/styles/Typography/FontSizes.js
UI updated for better readability, These includes:
1. Removed micro var usage for font-size.
2. Updated all existing mico font-size to tiny for better readability.
3. Font-sizes switched to use existing variables.
[UI update for better readability. #621](https://github.com/open-sauced/open-sauced/issues/621)
> Removed micro var usage && font-size switched to use existing variables

- package-lock.json
- package.json
- src/components/RepositoryGoals.js
fixes https://github.com/open-sauced/open-sauced/issues/830
> fixed the opensource.guide label

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
As an effort to prevent spam, we are requiring all sections not be removed from the template. Folks also need to link an issue using the keywords https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword.
> Update PULL_REQUEST_TEMPLATE.md to include reason to add invalid label

- README.md
This is just a version issue, there were some breaking changes introduced in 3.0.0 and one of them was "minimum supported Node.js version is 10.13.
1. Got to package.json
1. Change the version of terser-webpack-plugin to 2.3.6
1. Go to the terminal in the project directory
1. Do npm install
> fix: terser-webpack-plugin node support

- src/components/CreateGoals.js
- src/components/Repository.js
- src/components/RepositoryGoals.js
- src/styles/Grid/Flex.js
- src/styles/Grid/index.js
* Resolved excessive spacing around illustrations in three of the pages listed on the issue: 
1- Dashboard with repos
2- Dashboard without repos
3- Repositories
* The spacing was due to a Safari default item alignment, either "center" or "baseline". I resolved it by aligning items "flex-start".
* Created a new styled component called SpaceBetweenTop, based on SpaceBetween. The new styled component is in src > styles > grid > flex.js
* Replaced the styled component in three React Components:  
1- CreateGoals.js
2- RepositoryGoals.js
3- Repository.js
Fixes #756  https://github.com/open-sauced/open-sauced/issues/756
The fix on Safari Dashboard:
The fix on Safari Repos:
Fix doesn't affect mobile/responsive, which doesn't show an illustration : 
Mobile / Responsive on Chrome still work: 
Main …
> Safari UI vertical alignment fix, Illustrations top and bottom margins

- src/components/DangerZone.js
- src/components/Modal.js
- src/styles/Backdrop.js
- Deletion confirmation of repository
- Added a modal component with backdrop for reusability
- Added a translate transition when the modal is shown
- I am new to open source contributions so please inform me if something needs to be changed
> Delete repo confirmation modal with backdrop

- README.md
developer.github.com domain has migrated to docs.github.com
> Update link to GraphQL API v4 docs

- .github/workflows/ci.yml
- .github/workflows/lint-pr.yml
- .github/workflows/release-management.yml
- CHANGELOG.md
- CONTRIBUTING.md
- package-lock.json
- package.json
This adds:
(1) Contributing.md changes to explain to contributors how to add to the repo
~~(2) husky so that when a dev types git commit - we get the standardized commit messages~~ removed
(3) cz-conventional-changelog to build the changelog
(4) semantic release to allow for the automatic standardized generation of the changelog with npm run release
~~(5) modifications to package.json to config the above~~ cz and husky modifications removed
(6) addition of build process after merging, that runs npx release for you after merge to generate the CHANGELOG.md
Fixes #668 
Check the box given in this article here to enable pull_request_target needed in the lint-pr.yml file under workflows. link to article:  https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workf …
> feat: Create Changelog for Issue #668

- CONTRIBUTING.md
Fixed the TRIAGE_GUIDE.md link in CONTRIBUTING.md
Updated the CONTRIBUTING.md file to correct the TRIAGE_GUIDE.md link
n/a
n/a
> fix: TRIAGE_GUIDE.md link

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- src/lib/repoStatusCode.test.js
> fix: add note about pr validation

- src/components/ListGoals.js
- src/containers/App.js
- src/containers/Dashboard.js
Fixes: #789 by removing the issue_id from the end of the route that displays a particular repository. 
Fixes: #789
N/A
> fix: #789 - Repo goal url should be dependent on issue number existing

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/welcome.yml
All dependabot PRs are failing because of the welcome workflow.
> fix: prevent welcome check with dependabot

- .github/workflows/welcome.yml
- CHANGELOG.md
- package-lock.json
- package.json
1. Fixes welcome.yml
1. Runs release and bumps version
1. Generated Changelog (working)
> chore(release): 0.18.2

- src/components/Nav.js
- stories/4-Nav.stories.js
- stories/6-Home.stories.js
This is a very minor change that addresses the external links in the top nav-bar. Until now, only the `Issue` link triggered a new browser tab, but this PR makes every external link in the nav-bar like that.
There are no UI changes.
> fix: Links opening (in new tabs)

- package-lock.json
- src/components/DetailInfo.js
- src/components/Footer.js
- src/components/Hero.js
- src/components/IssueListItem.js
- src/components/ListGoals.js
- src/components/Repository.js
- src/index.css
- src/styles/Button.js
- src/styles/Card.js
- src/styles/EmptyPlaceholder.js
- src/styles/Header/AdminNav.js
- src/styles/Header/Heading.js
- src/styles/Header/Hero.js
- src/styles/Header/HomeNav.js
- src/styles/Header/SubHeading.js
- src/styles/Input.js
- src/styles/List.js
- src/styles/NotFound.js
- src/styles/Search.js
- src/styles/Select.js
- src/styles/TextArea.js
- src/styles/Typography/AccentLink.js
- src/styles/Typography/FontSizes.js
- src/styles/Typography/SubtleLink.js
- src/styles/variables.js
> fix: Increase UI readability by using relative sizes and comply to WCAG

- .github/CODEOWNERS
- CONTRIBUTING.md
> fix: Quick grammar fixes 

- .github/workflows/ci.yml
> chore: Update actions/cached to v2

- .github/funding.yml
- CONTRIBUTING.md
GitHub allows projects to display profiles for github sponsor profiles. In the future, I will ask folks to add their account after contributions are made. I will go through the list every quarter to remove folks who are no longer contributing.
> feat: Create funding.yml

- .github/workflows/pr-audit-target.yml
- src/components/Hero.js
- src/components/Nav.js
When I switch to a paid discord it broke the link everywhere. This is updating it to the correct link.
> fix: Update broken discord links everywhere

- package.json
> chore: Test tag automation

- .github/workflows/release-management.yml
- package.json
The npm run release is not committing to package.json update. Testing if this action will update it.
> fix: Patch release-management.yml (testing if this works)

- .github/workflows/release-management.yml
- package.json
After some testing, it looks like we need to push tags after running the release script. Going to add it to the script.
> fix: Explicitly publish commit with tags 

- .github/workflows/ci.yml
This pull request simply changes the CI dependency install command from `npm install` to `npm ci`. This should speed up the install process and also never be different from our production package.lock.json.
No UI changes!
Be happy and make the ones around you happy, too!
> ci: Freeze the lockfile in CI

- package-lock.json
For months have I seen that our browser list caniuse database was outdated, so I just ran `npx browserslist@latest --update-db`.
None that I know of.
For future reference, this is the guide on updating: https://github.com/browserslist/browserslist#browsers-data-updating
Just the good ol' terminal.
Carry on, and maybe update the DB every once in a while.
> chore: Update the caniuse database

- CONTRIBUTING.md
- README.md
This PR is for #957. When getting setup for a PR earlier this week, I ended up needing to install watchman to get the test suites to run.  Also set a few markdown code blocks for "sh" as language to be consistent.
N/A
> feat: Update README and CONTRIBUTING docs for watchman

- src/lib/apiGraphQL.js
- src/lib/persistedGraphQL.js
This is will help out @mtfoley with #456
> feat: adds persisted query for issues by labels.

- src/components/DangerZone.js
- src/styles/Backdrop.js
Changing wording to "remove" instead of "delete". I changed the confirm modal content, but CSS could still use some tweaking. Be advised I think this action is broken in production, but this PR shouldn't affect it.
Fixes #932
> refactor: change wording from "delete" to "remove"

- src/styles/Card.js
Fixes a vertical-align issue with the dot next to languages on repository pages
Fixes [#953](https://github.com/open-sauced/open-sauced/issues/953#issue-871386561)
> fix: Dot vertical alignment

- src/components/AddRepoForm.js
- src/components/RepositoryGoals.js
Adds an error for when you try to add the same repo twice on the dashboard page.
Fixes [#974](https://github.com/open-sauced/open-sauced/issues/974)
> fix: able to add the same repo twice

- src/components/Issues.js
- src/components/Repository.js
- src/lib/apiGraphQL.js
- src/lib/persistedGraphQL.js
fixes #971
https://www.loom.com/share/c1492ca3614644fd9f427f9a2baacfbd
#976
> fix: 971 pagination for issues

- src/lib/apiGraphQL.js
Fixed issue #865 where the goals caching was hardcoded to the master branch. Change made to pull from the default branch instead.
Fixes #865 Goals caching is hardcoded to master branch
N/A
No post-deployment tasks are needed
> fix: 865 Goals caching is hardcoded to the master branch

- src/components/Issues.js
- src/components/ListGoals.js
- src/components/Repository.js
- src/containers/App.js
- src/containers/Dashboard.js
The Repository page did not have the id for the issue available. This was removed while working a new feature that never shipped. 
- I add the issue number to the URL
- I now leverage that to identify the issue with the note. 
Fixes #955
Fixes #833
> fix: working note taking and deletion

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 0.18.11

- .github/workflows/release-management.yml
> fix: Update release-management.yml

- src/components/RepoListItem.js
Fixes mis-alignment between Star Icon and number of stars of a repo.
Fixes #991
> fix: mis-aligned Star on the repo list

- .github/release-notes.yml
> fix: Release note tagging

- src/lib/util.js
Fixes #1007 by checking URL.hostname.  I tried to refactor this file down to a single function and the test suite convinced me I was being too clever.
> refactor: Use URL.hostname

- .github/workflows/ci.yml
Cache doesn't work with `npm ci` and is bad pratice on production builds. Not sure we would have much benefit from it outside of pull requests.
Updated to `npm@7` to make everything forward compatible.
Should magically unblock #1011 
Does testing this on my fork work if I just enable actions to build from settings ?
> fix(actions): removed failing production cache and updated npm

- src/lib/apiGraphQL.js
Fixes #1014  by bumping GQL to first 50 items.
> fix: malformed goal urls over 10

- src/components/CreateGoals.js
#948 by adding a link to user's newly created open-sauced-goals repo. As mentioned in issue commentary, redirect to this repo after installation steps may require passing state to app's OAuth flow along with configuration changes to the open-sauced GitHub app itself.
> feat: Add link to user's open-sauced goals

- CHANGELOG.md
- docs/dark-mode.md
- package-lock.json
- package.json
> feat: dark mode docs

- TRIAGE_GUIDE.md
My philosophy on `good first issues` is that they should include solutions or helpful tips to point folks to ways to solve the problems relatively easily. 
- Issues that `needs triage` cannot be labeled as `good first issues`
- It is better to have no `good first issues` labeled than to have a `good first issue` confusing enough to deter a contributor from contributing.
> docs(good first issues): updates triage guide

- src/images/darkMode.svg
This PR fixes a Safari SVG bug.
Fixes #1048
> fix: safari bug

- src/styles/List.js
This PR fixes bug #1045 . 
#1045
> fix: dark mode dashboard hover

- src/components/ListGoals.js
- src/index.css
- src/styles/Search.js
fix: This PR fixes dashboard search bar overlap mobile bug by integrating some CSS in search style and sort option. 
fixes #1046
> fix: 1046-fix-dashboard-search-bar-overlap-mobile

- docs/learnwithjason.md
This PR address #1072 . 
re #1072
This is step one of several to address #1072
> docs: add a Learn With Jason doc

- src/styles/Header/Hero.js
This PR fixes the fonts when a user is logged out by removing the references to the Arvo font in "src/styles/Header/Hero.js".
Fixes #1042
> fix: fonts when user is logged out

- .github/workflows/ci.yml
This PR fixes #1080 
Fixes #1080
> fix: pin down actions/node-setup to v2.1.5

- .github/workflows/assign-yourself.yml
This PR adds the comment feature described in #1077, using new feature in bdougie/take-action
Verify
> feat: comment for assign yourself

- .github/workflows/ci.yml
This PR fixes docusaurus build.
> fix: add proper folder to docusaurus build

- docs/docs/styling/dark-mode.md
- docs/docusaurus.config.js
This PR addresses these following issues:
- Some parts of the dark mode docs were a tiny bit confusing with the wording
- Hitting the <kbd>Edit this file</kbd> button led to a 404
N/A
N/A
Na-da
](https://media.giphy.com/media/hQKEDZ9X9pCPeRq5lJ/giphy.gif)
> docs: Docs and Docosaurus fixes

- docs/docusaurus.config.js
- src/components/Nav.js
-  Description
This PR addresses the issues:
- Adding feature to switching the [docs](https://docs.opensauced.pizza/) on top right corner
Fixes #1089 
but on the docs it need to tested out, I don't know how to edit the [docs](https://docs.opensauced.pizza/) to add home button
N/A
> feat: add button to switch the documentation

- docs/docs/contributing/fetching-data-from-github.md
Fixing a handful of typos and tweaking a few other words
This PR fixes #1100
> docs: update data fetch docs

- docs/docs/contributing/fetching-data-from-github.md
We need to run `npm run build` sort of before the release or ensure we test it works locally.
This PR fixes #1100 
Fixes #1100
> fix: add closing tags to docs break tags

- docs/docusaurus.config.js
- docs/npm-shrinkwrap.json
- docs/package.json
Updating docusaurus config per Algolia settings provided in #1106. 
This PR fixes #1106 
Test whether algolia search works!
> feat: update docusaurus config for Algolia

- scripts/build.js
CI is set to true on github actions - warnings trigger errors. Did not previously use the static build to create docker so we never actually ran into this error.
Really fixes #1107
> fix: correct production environment variables

- package.json
> build: correct requirements for semantic-release

- src/components/DropdownMenu.js
- src/components/Nav.js
- src/styles/Card.js
- src/styles/Header/HomeNav.js
- src/styles/ProfileAvatar.js
- stories/2-Card.stories.js
This is my first pr to open source 🎉 
This PR adds a dropdown menu feature. 
Prior to this PR, when you clicked on your avatar in the top right-hand corner, it would immediately redirect you to your GitHub profile. Additionally, the logout button was on the navigation bar when logged in.
With the changes in this PR you now:
1. Click your avatar and get a dropdown menu with:  
- your github name where you will be redirected to your github profile if clicked
- A logout link
- The app version (I wasn't sure if I should do this because I know the admin nav may have these details, but the ticket suggested I add some info about the app. This is all the app info that I knew how to get)
2. Hover states:
- If you hover over the links, it will indicate that you hovered by turning a lighter shade of …
> feat: added a dropdown menu under avatar

- src/components/DropdownMenu.js
- src/styles/Card.js
- src/tests/DropdownMenu.test.js
This PR includes a test for the dropdown menu component that opens underneath the avatar. The tests indicated that I neglected to add `< ul >  < /ul> ` tags for the list elements in my dropdown, so I included ul tags and the css needed for them as well. This is not a feature..it's just a test for a feature. 
Fixes #1134 
no visual changes
nope.
> feat: add tests for dropdown menu

- README.md
The link in the README.md for contributing guide was broken which I replaced with https://docs.opensauced.pizza/contributing/getting-started/
Closes #1136
> fix: broken link for contributing guide

- src/components/RecommendedRepoItem.js
- stories/2-Card.stories.js
This PR adds this feature: #1142. 
- I tried to stay consistent with the UI that appears to be that whenever a link did not include hovering over the entire row the link contained the text-decoration to signify that it was a link. If this is incorrect or the text-decoration style should be none  I will fix it.
- I also updated the storybook item to use the component.
Fixes #1142 
There are no post-deployment tasks that need to be performed.
> feat: link repo recommendations to their repositories

- npm-shrinkwrap.json
- package.json
- src/components/ListGoals.js
- src/tests/ListGoals.test.js
Attempts to refactor out direct dependency on lodash library.  Downstream deps still call for it.
Closes #1157 .
May affect #832 and/or #986 
Adjusted tests to reflect `data` prop of ListGoals component.
> refactor: remove lodash dep

- src/components/NoteFormSocial.js
This PR changes the basic template to a link instead of a button.
Closes #1159 
- Add prettier config file as each system has it's own config. Due to which a large portion of a file gets changed.
- After doing changes in ``NoteFromSocial.js`` as soon page reloads it crashes. Need to find a solution.
> feat: change note form basic template to a link

- .github/workflows/compliance.yml
This PR makes the `compliance.yml` workflow reusable.
Seen this on [GitHub Universe](https://www.youtube.com/watch?v=SFOn5JyKhPY&t=337s), missed it in [the docs](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows).
> ci: make compliance workflow re-usable

- .github/workflows/compliance.yml
- .github/workflows/release.yml
This PR adds workflow reusability across multiple repositories and removes the lint command from the release flow.
> ci: improve workflow reusability across repositories

- README.md
This PR fixes the README.md contributing guide link.
Fixes #1298
No
N/A
> fix: fixed README.md contributing guide link

- .github/workflows/compliance.yml
Update pr-compliance-action to a version that should strip HTML comments out of PR description so it doesn't find false positives.
This PR fixes #1302
> fix: update pr-compliance-action

- .czrc
- npm-shrinkwrap.json
- package.json
This PR removes the commitizen extraneous file and updates dependencies.
> build: update dependencies and remove extraneous files

- src/components/CommitType.js
Change color of closed issue icon to purple
This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 
Fixes #1321
> style: change IssueClosedIcon from gitRed to gitPurple

- .github/workflows/development.yml
- Dockerfile
This PR makes releases work again :/
> fix: correct docker build

- .github/workflows/release.yml
This PR is just trying to recover from unknown error last release.
> build: attempt to unblock releases

- .github/workflows/triage.yml
This is basically the same thing as the[ PR that I merged for the hot repo](https://github.com/open-sauced/hot/pull/77) .
I created an earlier PR for the [Take Action](https://github.com/bdougie/take-action/pull/8). A comment will be created if the issue is already assigned to a previous contributor. This PR contains the messaging of the comment. The comment will say: "Thanks for being interested in this issue. It looks like this ticket is already assigned to a contributor. Please communicate with the assigned contributor to confirm the status of the issue."
Please let me know if you want to change the wording of the comment. 
No issue is opened for this, but this is related to this [issue ](https://github.com/bdougie/take-action/issues/7) and this …
> fix: content related to take action update

- src/components/CreateGoals.jsx
- src/components/RepositoryGoals.jsx
This PR fixes the issue with new users unable to create goals repos. Turns out when a repo does not exist, the ternary was only checking for an error and this is technically not an error.  
fixes #1411
> fix(onboarding-broke): new user onboarding was broken, sort of

- src/components/CreateGoals.jsx
- src/components/RecommendedRepoItem.jsx
- src/components/RepositoryGoals.jsx
- stories/6-Home.stories.js
This PR fixes storybook deployment and removes some `console.log`s.
> fix(storybook): correct hero component name change and some stray console logs

- src/styles/Footer.jsx
This PR corrects the footer on light mode.
> fix: make footer visible in light mode

- src/components/Repository.jsx
This PR [removes] the [feature] contributions. 
Resolves #1420
> fix: Removed the Contributions component.

- src/components/Card.jsx
- src/components/CreateGoals.jsx
- src/components/Repository.jsx
- src/styles/Button.jsx
- src/styles/Card.jsx
- src/styles/Container.jsx
- src/styles/Grid/Flex.js
This PR [adds] the [feature] of redesigning the experience of how a new user joins Open Sauced. 
Fixes #862
> feat: Redesigning the Onboarding experience

- src/components/ListGoals.jsx
- src/components/Repository.jsx
- src/containers/App.jsx
- src/containers/Dashboard.jsx
- src/tests/ListGoals.test.js
In response to issue #1424, this PR makes the following changes:
- pulls issue ID references and dependent components out of Repository.jsx
- updates state for whether to show any kind of fork button ("Fork" or "View Fork")
- updates Route in App.jsx not to look at issue number, and to allow viewing repos
without being logged in, but still passing user through
- updates Route in Dashboard.jsx not to look at issue number
- updates ListGoals component not use goal number
- updates tests for ListGoals component, including having links without goal number
Resolves #1424 
Repository, URL does not contain issue number, user logged out:
Repository, URL does not contain issue number, user logged in:
ListGoals, link does not contain issue number.
N/A
> feat: no issue id in url

- npm-shrinkwrap.json
- package.json
- src/components/CreateGoals.jsx
- src/index.jsx
- src/lib/analytics.js
This PR [adds] the [feature] posthog logging. 
Resolves #1430 and resolves #1434
> feat: Install PostHog and implement data capture on various buttons

- .github/workflows/storybook.yml
This PR [adds/removes/fixes/replaces] the [feature/bug/etc].
> fix: storybook deploys

- src/components/CreateGoals.jsx
- src/components/RepositoryGoals.jsx
- src/styles/Header/CreateGoalsRepoNav.js
- src/styles/Header/index.js
- stories/8-Onboarding.stories.js
This PR adds the feature of repo suggestions in onboarding. 
Adds #1428
> feat: Adds Repo suggestions to the onboarding flow

- src/lib/util.js
This PR fix #1451 
ots/Recordings
> fix: able to add repo name with "."(dot) in it issue#1451

- .github/workflows/codeql-analysis.yml
Fix CodeQL scanning version based on this post.
[Code scanning: deprecation of CodeQL Action v1](https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/#exactly-what-do-i-need-to-change)
This PR [adds/removes/fixes/replaces] the [feature/bug/etc].
> ci: Update the CodeQL version to V2

- src/components/Repository.jsx
- src/lib/apiGraphQL.js
This PR fixes the bug in which on clicking the Fork button, it doesn't actually create a fork but still converts into View Fork button, resulting in leading to a 404 page as no fork was created.
This PR converts the Fork button into a link that leads to the Github repo's "Create Fork" page.
Fixes #1461
> fix: switch forking function with github link template

- .github/workflows/compliance.yml
> fix: Update broken contributing links

- src/components/ListGoals.jsx
- src/components/RecommendedRepoItem.jsx
- src/components/RepositoryGoals.jsx
- stories/2-Card.stories.js
This PR fixes the bug #1219 by preventing a duplicated repo from being added and then skipping over any duplicated repos that might have been previously created as a result of this bug.
Fixes #1219
> fix: Duplicate repositories can be added to dashboard

- .github/workflows/codeql-analysis.yml
- .github/workflows/compliance.yml
- .github/workflows/development.yml
- .github/workflows/maintenance.yml
- .github/workflows/release.yml
- .github/workflows/storybook.yml
- .github/workflows/triage.yml
This PR adds artifact maintenance and sensible timeouts to all jobs.
closes #1469
> feat: add artifact maintenance and global jobs timeout

- .gitignore
- src/components/RepositoryGoals.jsx
- src/styles/Card.jsx
- src/styles/Grid/Flex.js
This PR removes margins between cards on the dashboard and repository screen
Fixes #1422 
> **Note**
> All these borders were removed :sweat_smile: 
| ![dashboard_before](https://user-images.githubusercontent.com/79809121/197895093-3d9783f9-3c7f-478c-b69b-9e9b1ea4b79c.png) 	| ![dashboard_after](https://user-images.githubusercontent.com/79809121/197895130-f0821c4e-d79b-40c4-965b-dc2edf06591f.png) 	|
|----------------------------------------------------------------------------------------------------------------------------	|---------------------------------------------------------------------------------------------------------------------------	|
| ![repo_before](https://user-images.githubusercontent.com/79809121/197895188-6b25ae80-c924-4334-a54e-9b58376bccb5.png)      	| …
> fix: weird spacing on the dashboard and repo screen

- README.md
> docs: fix repository typo
